name: Deploy React Applications to AKS using GitHub Actions
#on: # Disabling actions. To enable, remove comment
  push
  
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Docker Image for Development Environment
        run: docker build -t nishkarshraj/demoaks .

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        
      - name: Docker Push
        run: docker push nishkarshraj/demoaks
      
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE }}'
          cluster-name: nishkarshraj
          resource-group: nish
        
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
            ingress.yaml
          namespace: default
